# Generated by Django 2.1.5 on 2019-02-02 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20190131_2342'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='process',
            name='feedback',
        ),
    ]
